### ISSUE TITLE
cleancss, command not found if global isn't used while installing clean-css-cli

### ISSUE THREAD

**Issue by igauravsehrawat** [clean-css/clean-css-cli#13]
Hi,
Awesome tool.

`cleancss` isn't available on command line unless I install it globally. Pasting output for problem.
```
➜  Server git:(minify-assests) ✗ npm install --save clean-css-cli
~/Server
└── clean-css-cli@4.1.6 

➜  Server git:(minify-assests) ✗ cleancss
zsh: command not found: cleancss
```

In the documentation it's mentioned to install it locally using ` npm install clean-css-cli`. Is it intended behavior? 

I am using macOS, Sierra v10.12.4.

Thanks

**Comment by igauravsehrawat** [comment]
`uglifyjs` works good though, no need for global install option.

**Comment by jakubpawlowicz** [comment]
Hmmm, I installed uglifyjs with `npm i uglify-js` and `bash` can't pick it up either. How does it work in `zsh`? What does `which uglifyjs` yield for you?

**Comment by igauravsehrawat** [comment]
@jakubpawlowicz 

Thanks for replying.

Extremely sorry for providing wrong info, you are right `uglifyjs` also doesn't work. I had two node version installed and that created confusion.

So the documentation has to be fixed, right? Submit a PR?

Thanks

**Comment by jakubpawlowicz** [comment]
Yes, we need to make it clear only the global install puts cleancss in the global $PATH. PRs are always welcome!

**Comment by jakubpawlowicz** [comment]
Closing as 'won't fix' as clean-css-cli is going into maintenance mode. If anyone wants to bring it back up, please submit a PR.
