### ISSUE TITLE
Any plan to support --watch?

### ISSUE THREAD

**Issue by plantain-00** [clean-css/clean-css-cli#15]

**Comment by jakubpawlowicz** [comment]
What are the other options here as I'm not familiar with the matter. Anyway PRs are always welcome.

**Comment by ilog2000** [comment]
@plantain-00 means that CLI packages can be run with --watch option to track changes in uncompressed file and re-execute minification. A good example is 'myth' package (it is broken now with node v6+). Current work around for me is 'onchange' package. You can look inside their code.

**Comment by jakubpawlowicz** [comment]
I'd be interested in adding it to CLI as it's a rather common feature.

**Comment by dnovacik** [comment]
+1

**Comment by Daeamon** [comment]
+1

**Comment by christiankozalla** [comment]
Hey @jakubpawlowicz

I am going to tackle this issue. I've just experimented a little bit with chokidar and it is working with a single file input.
Now I am trying to make it work for batches. Hoping to submit a PR soon!

**Comment by jakubpawlowicz** [comment]
Thanks @christiankozalla - let me take a look at the PR.

**Comment by jakubpawlowicz** [comment]
Closing this a version 5.5 includes the functionality.
