### ISSUE TITLE
feature request: configuration file

### ISSUE THREAD

**Issue by basbebe** [clean-css/clean-css-cli#20]
I would love to be able to include an external configuration file.
Minifiers like `uglifyjs` to `html-minifier` allow to use `-c ./filename` to include separate configurations (which could then be shared with other utilities in different development stages.
Users then could store their configs in e.g. a `.cleancssrc` file.

**Comment by SamuelJohnsonMedia** [comment]
This would be great, my cli options in package.json are becoming very unwieldy and hard to view/edit

**Comment by jakubpawlowicz** [comment]
Closing as 'won't fix' as clean-css-cli is going into maintenance mode. If anyone wants to bring it back up, please submit a PR.
