### ISSUE TITLE
feature request: source map rebase

### ISSUE THREAD

**Issue by ashucg** [clean-css/clean-css-cli#25]
It would be great to have an option similar to uglifyjs, which allows rebasing source map source URLs/paths. Right now source map has sources path relative to my working directory - where I am using CLI and there is no way to change it.

**Comment by rbaras** [comment]
+1

**Comment by jakubpawlowicz** [comment]
Closing as 'won't fix' as clean-css-cli is going into maintenance mode. If anyone wants to bring it back up, please submit a PR.
