### ISSUE TITLE
Respect `breaksWith` option

### ISSUE THREAD

**Issue by XhmikosR** [clean-css/clean-css-cli#26]
@jakubpawlowicz: I make this to track the line endings issue which is noticeable on Windows.

https://github.com/jakubpawlowicz/clean-css-cli/blob/master/index.js#L249

The above line doesn't take into account the `breaksWith` option.

**Comment by XhmikosR** [comment]
Refs https://github.com/jakubpawlowicz/clean-css/issues/964

**Comment by XhmikosR** [comment]
@jakubpawlowicz: this is the offending line https://github.com/jakubpawlowicz/clean-css-cli/blob/master/index.js#L263

I tried checking for `options.format.breakWith` but that didn't work.

```
console.log(options.format); // breakWith=lf
```

**Comment by jakubpawlowicz** [comment]
Closing as 'won't fix' as clean-css-cli is going into maintenance mode. If anyone wants to bring it back up, please submit a PR.
