### ISSUE TITLE
Not minifying when @import file has timestamp

### ISSUE THREAD

**Issue by rdotg** [clean-css/clean-css-cli#35]
When there is a query param on a css file (_in this case a timestamp_), clean-css-cli will not minify the current file. As soon as I remove the query param, it minifies the file. My goal is to ignore the @import statement but still minify the file.

I tried passing every conceivable option to prevent the clean css from processing this line:

```
@import url(font_awesome.css?t=1554926691456);
```

But it throws the error:

```
Ignoring local @import of "font_awesome.css?t=1554926691456" as resource is missing
```

**Comment by jakubpawlowicz** [comment]
Closing as 'won't fix' as clean-css-cli is going into maintenance mode. If anyone wants to bring it back up, please submit a PR.
