### ISSUE TITLE
Add a Windows test environment

### ISSUE THREAD

**Issue by jakubpawlowicz** [clean-css/clean-css-cli#52]
Via AppVeyor as in [clean-css](https://github.com/jakubpawlowicz/clean-css/blob/master/appveyor.yml)?

**Comment by XhmikosR** [comment]
Nope, GitHub Actions is fine :)

**Comment by jakubpawlowicz** [comment]
Closing as 'won't fix' as clean-css-cli is going into maintenance mode. If anyone wants to bring it back up, please submit a PR.
