### ISSUE TITLE
Switch to async fs methods

### ISSUE THREAD

**Issue by XhmikosR** [clean-css/clean-css-cli#60]
Since Node.js is single-threaded, switching to async fs methods should make everything as fast as possible. The only exception AFAICT is `fs.existsSync`. While at it, it would definitely be worth switching to `glob` (async).

**Comment by jakubpawlowicz** [comment]
Closing as 'won't fix' as clean-css-cli is going into maintenance mode. If anyone wants to bring it back up, please submit a PR.
