### ISSUE TITLE
RemoveQuotes not working

### ISSUE THREAD

**Issue by ferranbonas** [clean-css/clean-css-cli#72]
Hello, last week I upgraded cleancss version from 3.1.9 to 5.3.3

Now I'm getting different behaviour after using cleancss on the same source file. The quotes inside an "url" function aren't removed.

For example this source css:
```
@font-face {
    font-family: 'Catamaran';
    font-weight: 300;
    font-style: normal;
    src: local('Catamaran Light'),
    local('Catamaran-300'),
    url('/fonts/Catamaran-300/Catamaran-300.woff2') format('woff2'),
    url('/fonts/Catamaran-300/Catamaran-300.woff') format('woff');
    font-display: swap;
}
```
In cleancss 3.1.9 result:
`@font-face{font-family:Catamaran;font-weight:300;font-style:normal;src:local('Catamaran Light'),local('Catamaran-300'),url(/fonts/Catamaran-300/Catamaran-300.woff2)format('woff2'),url(/fonts/Catamaran-300/Catamaran-300.woff)format('woff');font-display:swap}`

In cleancss 5.3.3 (cleancss fonts.css -o fonts.cleaned.css or cleancss fonts.css -O1 -o fonts.cleaned.css):
`@font-face{font-family:Catamaran;font-weight:300;font-style:normal;src:local('Catamaran Light'),local('Catamaran-300'),url('/fonts/Catamaran-300/Catamaran-300.woff2') format('woff2'),url('/fonts/Catamaran-300/Catamaran-300.woff') format('woff');font-display:swap}`

I tried:  `cleancss fonts.css -O1 removeQuotes:on -o fonts.cleaned.css`, also  options like urlQuotes:false, but always I get quotes on the output. Using double quotes inside url() also keeps them in output.

**Comment by jakubpawlowicz** [comment]
Closing as 'won't fix' as clean-css-cli is going into maintenance mode. If anyone wants to bring it back up, please submit a PR.
