### ISSUE TITLE
Read CSS file from stdin

### ISSUE THREAD

**Issue by SabrinaJewson** [clean-css/clean-css-cli#75]
Would it be possible to run `cleancss` such that it reads the CSS file from the standard input instead of a named file? My CSS file is being generated dynamically it would be easier if I could avoid having to write out to a temporary file. I tried `cleancss -` but it doesn't seem to work:

```
ERROR: Ignoring local @import of "-" as resource is missing.
```

**Comment by jakubpawlowicz** [comment]
Hi @SabrinaJewson - is piping your CSS file to clean-css an option, e.g. `echo 'a{color:#f00}' | cleancss`? This is one of the ways clean-css is tested, e.g. https://github.com/clean-css/clean-css-cli/blob/master/test/binary-test.js#L71 - `pipedContext` is defined next to the top of the file.

**Comment by jakubpawlowicz** [comment]
No problem, cheers!
