### ISSUE TITLE
Negated pattern throws `zsh: event not found: css/`

### ISSUE THREAD

**Issue by crstauf** [clean-css/clean-css-cli#85]
This is probably specific to my setup somehow, but 🤷‍♂️ .

```
$ cleancss --batch css/*.css !css/*.min.css
zsh: event not found: css/
```

**Comment by crstauf** [comment]
Yep, a few minutes after publicly posting my issue, found the solution: always happens. 🤦‍♂️ 

https://unix.stackexchange.com/questions/33339/cant-use-exclamation-mark-in-bash

```
$ cleancss --batch css/*.css '!css/*.min.css'
```

**Comment by jakubpawlowicz** [comment]
No worries, glad you did, and it'll hopefully help someone else!
